export const curriculum = [
  {
    slug: "guide1-calcul-numerique",
    name: "Guide 1 - Calcul numerique",
    topics: [
      "relatifs_signes",
      "priorites_operatoires",
      "fractions",
      "puissances",
    ],
  },
  {
    slug: "guide1-calcul-litteral",
    name: "Guide 1 - Calcul litteral",
    topics: ["calcul_litteral_reduction", "developpement", "identites_remarquables", "factorisation_facteur_commun", "factorisation_identites"],
  },
  {
    slug: "guide1-algebre",
    name: "Guide 1 - Equations et proportionnalite",
    topics: ["equations", "inequations", "proportionnalite", "pourcentages"],
  },
  {
    slug: "guide1-geometrie",
    name: "Guide 1 - Geometrie",
    topics: ["pythagore", "pythagore_reciproque", "geometrie_milieux", "coordonnees_milieu", "vecteurs_chasles"],
  },
  {
    slug: "guide1-donnees-espace",
    name: "Guide 1 - Statistiques et espace",
    topics: ["statistiques_moyenne", "statistiques_frequence", "grandeurs_espace"],
  },
  {
    slug: "sa1-legacy",
    name: "Legacy - Triangles",
    topics: ["nombres-reels", "valeur-absolue", "trigonometrie", "thales", "reciproque-thales", "triangles-semblables", "triangle-rectangle", "angles-cercles"],
  },
  { slug: "sa2-legacy", name: "Legacy - Configurations de l'espace", topics: ["cone", "sections-planes"] },
  {
    slug: "sa3-legacy",
    name: "Legacy - Calcul litteral",
    topics: ["polynomes", "equations-droite", "vecteurs", "coordonnees-vecteurs"],
  },
  {
    slug: "sa4-legacy",
    name: "Legacy - Organisation des donnees",
    topics: ["applications-affines", "applications-lineaires", "statistique"],
  },
] as const;

export const topicLabels: Record<string, string> = {
  relatifs_signes: "Regles de signes",
  priorites_operatoires: "Priorites operatoires",
  fractions: "Fractions",
  puissances: "Puissances",
  calcul_litteral_reduction: "Calcul litteral - reduction",
  developpement: "Developpement",
  identites_remarquables: "Identites remarquables",
  factorisation_facteur_commun: "Factorisation - facteur commun",
  factorisation_identites: "Factorisation - identites remarquables",
  equations: "Équations",
  inequations: "Inéquations",
  proportionnalite: "Proportionnalite",
  pourcentages: "Pourcentages",
  pythagore: "Pythagore",
  pythagore_reciproque: "Reciproque de Pythagore",
  geometrie_milieux: "Geometrie des milieux",
  coordonnees_milieu: "Coordonnees du milieu",
  vecteurs_chasles: "Vecteurs et relation de Chasles",
  statistiques_moyenne: "Statistiques - moyenne",
  statistiques_frequence: "Statistiques - frequence",
  grandeurs_espace: "Grandeurs et espace",
  "nombres-reels": "Nombres reels",
  "valeur-absolue": "Valeur absolue",
  trigonometrie: "Trigonometrie",
  thales: "Thales",
  "reciproque-thales": "Reciproque de Thales",
  "triangles-semblables": "Triangles semblables",
  "triangle-rectangle": "Triangle rectangle",
  "angles-cercles": "Angles et cercles",
  cone: "Cone",
  "sections-planes": "Sections planes",
  polynomes: "Polynomes",
  "equations-droite": "Equations de droite",
  vecteurs: "Vecteurs",
  "coordonnees-vecteurs": "Coordonnees de vecteurs",
  "applications-affines": "Applications affines",
  "applications-lineaires": "Applications lineaires",
  statistique: "Statistique",
};
